version: '3'
services:
  apigateway:
    image: gwangjang/apigateway
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://3.34.93.53:8761/eureka/
    ports:
      - 8888:8888
    networks:
      - msa-network

networks:
  msa-network:

