name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: make application.yml
      shell: bash
      run: |
        mkdir ./src/main/resources
        cd ./src/main/resources
        touch ./application.yml
        echo "${{ secrets.APPLICATION }}" > ./application.yml

    - name: Grant execute permission for gradlew
      run: sudo chmod +x gradlew

    - name: Build with Gradle
      run: sudo ./gradlew build -x test

    - name: Docker build
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t app .
        docker tag app ${{ secrets.DOCKER_USERNAME }}/eureka:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/eureka:latest
    
    - name: docker-compose.yml 
      uses: appleboy/scp-action@master
      with:
          username: ec2-user
          host: ${{ secrets.AWS_HOST }}
          key: ${{ secrets.AWS_KEY }}
          port: ${{ secrets.AWS_PORT }}
          source: "./docker-compose.yml"
          target: "/home/ec2-user/"
          
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} 
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }} 
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/apigateway:latest
          docker image prune -a -f
   
